# Generated by Django 4.1 on 2022-09-11 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appmensajes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
